# Generated by Django 3.1.4 on 2021-12-08 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='main.video'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='video', upload_to='media'),
        ),
    ]
