# Generated by Django 3.1.4 on 2021-12-10 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211210_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='video',
        ),
    ]
